### PR TITLE
Create maistra 2.5 merging google jwt_verify_lib "c29ba4b" 

### PR DESCRIPTION
**Pull request by dcillera**
Maistra 2.5 has been created by merging Google jwt_verify_lib "c29ba4b" into Maistra 2.4. 
This is necessary to build Maistra Envoy 2.5 (aligned to upstream v1.26.6).

### CODE REVIEW

**Comment by twghu** [comment]
This doesn't seem right, the patches don't appear and there appear to be too many files for the changes.

Check the version used as a basis for this.

**Comment by dcillera** [comment]
The Google version I merged into Maistra 2.4 is c29ba4b that is what is present in 1.26:

https://github.com/envoyproxy/envoy/blob/a510c8fdbf87860225311e136501421490fc1822/bazel/repository_locations.bzl#L765

The latest  Google commit merged by Otto into 2.4 had been  26c22c0ce1bc607eec8fa5dd26b707378adc7a88.

From 26c22c0ce1bc607eec8fa5dd26b707378adc7a88 to c29ba4b there are 57 commits that are those listed in the PR.

As regards  patches, we have to clarify because I realised they don't fit into the resulting code above while some of the modifications in them are already present.

**Comment by dcillera** [comment]
I've added modifications related to Tim's patches produced for envoy-openssl.

**Review by tedjpoole — APPROVED** [review]
LGTM

**Comment by jwendell** [comment]
Can we merge this?

**Pull request merged**
